use sakila;

-- List the number of films per category

select count(category_id) as category_count
from category
inner join film_category
using (category_id)
group by category_id;

-- Retrieve the store ID, city, and country for each store.

select store_id, city, country
from country
inner join city
using(country_id)
inner join address
using (city_id)
inner join store
using(address_id)
group by store_id;

-- 1 Lethbridge Canade
-- 2 Woodbridge Australia

-- Calculate the total revenue generated by each store in dollars.

select store_id, sum(amount) as total_amount
from inventory
inner join rental
using(inventory_id)
inner join payment
using(rental_id)
group by store_id;
-- 1 33679.79
-- 2 33726.77

-- Determine the average running time of films for each category

select category_id, name, avg(length) as avg_length
from film
inner join film_category
using(film_id)
inner join category
using(category_id)
group by category_id;

-- Bonus Identify the film categories with the longest average running time.

select category_id, name, max(length) as max_length
from film_category
inner join film
using(film_id)
inner join category
using(category_id)
group by category_id, name;